[package]
name = "core"
version = "0.1.0"
authors = ["David Drugeon-Hamon <zebeurton@gmail.com>"]
edition = "2021"
description = "The application core code"

[dependencies]
utils = { path = "../utils" }
log = "0.4.21"
